### PR TITLE
profile generate

### PR DESCRIPTION
**Pull request by DragonUncaged**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by DragonUncaged** [comment]
> elaborate on what this extension does

It Generates Different Profile Icons Only.

**Review by ridsuteri — CHANGES_REQUESTED** [review]
Please add a demo image of this extension

**Comment by DragonUncaged** [comment]
> Please add a demo image of this extension

demo video. ? how to use extension

**Comment by ridsuteri** [comment]
> > Please add a demo image of this extension
> 
> demo video. ? how to use extension

An image that shows the extension, which can give an idea about how the extension looks

**Comment by DragonUncaged** [comment]
> > > Please add a demo image of this extension
> > 
> > 
> > demo video. ? how to use extension
> 
> An image that shows the extension, which can give an idea about how the extension looks

added it

**Review by ridsuteri — APPROVED** [review]

**Pull request merged**
