### PR TITLE
News Extension Enhancement added

### PR DESCRIPTION
**Pull request by shreya024**
### 👨‍💻 Changes proposed

-Added html,css,js for news extension enhancement
-Added images of new extension

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
img2

### CODE REVIEW

**Comment by praniti111** [comment]
@shreya024 I see the extension fetches data from the sites which has its content in languages other than English, do mention if you could fetch data from the sites which have its content in English.

**Comment by shreya024** [comment]
> @shreya024 I see the extension fetches data from the sites which has its content in languages other than English, do mention if you could fetch data from the sites which have its content in English.

I have made required changes to make sure news fetched is in English only

img2

**Comment by shreya024** [comment]
@praniti111 Kindly review now

**Review by ridsuteri — APPROVED** [review]
good job @shreya024 :)

**Comment by shreya024** [comment]
> good job @shreya024 :)

Thank you :)

**Pull request merged**
