### PR TITLE
Open Tabs on Left - Chrome Extension [Utility]

### LINKED ISSUE #335: Open Tabs on Left - Chrome Extension
### Is your feature request related to a problem? Please describe.

- Open Tabs on left Chrome Extension 

### Describe the solution you'd like.

- An implemented Chrome extension would solce 

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #335 

### 👨‍💻 Changes proposed
- Added Chrome Extension [Utility] for Opening Tabs on left 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by praniti111** [comment]
@hariketsheth Kindly add the working screenshots and also steps on how to use the extension in the readme file.

**Comment by hariketsheth** [comment]
# Screenshots

## Before
image


## After
image


image

**Comment by hariketsheth** [comment]
Review this PR @praniti111 @ridsuteri

**Comment by hariketsheth** [comment]
> correct me if I am wrong @hariketsheth but I think this extension just adds that new tab on the left side of the currently open window right? and if so I don't think it's of any much use :( So I am closing this PR

You are right ! No issues Thanks

**Pull request closed without merging**
