### PR TITLE
Paint cum notes extension

### PR DESCRIPTION
**Pull request by Girlwithasmile**
### 🛠️ Fixes Issue
#77 

### 👨‍💻 Changes proposed
I've tried to create a paint cum quicknotes extension. Pls let me know if any changes required.

### ✔️ Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2022-03-14 175726
Paintextension

### CODE REVIEW

**Comment by praniti111** [comment]
- Firstly @Girlwithasmile rename the file [Paintextension.json] to manifest.json as it shows this error while testing the extension.

- Secondly Please give a brief description of how to use the extension you have made(A few bullet points on steps)

- as this is the template which appears, Do check out the changes.

Paint cum notes extension by Girlwithasmile · Pull Request #110 · ridsuteri_Awesome-Chrome-Extensions - Google Chrome 15-03-2022 02_53_00

**Comment by praniti111** [comment]
- Firstly @Girlwithasmile rename the file [Paintextension.json] to manifest.json as it shows this error while testing the extension.

- Secondly Please give a brief description of how to use the extension you have made(A few bullet points on steps)

- as this is the template which appears, Do check out the changes.

Paint cum notes extension by Girlwithasmile · Pull Request #110 · ridsuteri_Awesome-Chrome-Extensions - Google Chrome 15-03-2022 02_53_00

**Comment by ridsuteri** [comment]
> @Girlwithasmile, the extension is not working on my side(unable to find any drawing area and notes are also not saving...)Please check once again :((

any updates on this?

**Comment by Girlwithasmile** [comment]
> > @Girlwithasmile, the extension is not working on my side(unable to find any drawing area and notes are also not saving...)Please check once again :((
> 
> any updates on this?

Is it working on your side now?

**Comment by ridsuteri** [comment]
nopes :((

**Pull request closed without merging**
