### PR TITLE
Adding CountDown Timer

### PR DESCRIPTION
**Pull request by kalashvasaniya**
Hey I made CountDown Timer Project Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@kalashvasaniya please remove '.' from the end of the folder name because it is causing issues while locally cloning and testing the code.

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya please remove '.' from the end of the folder name because it is causing issues while locally cloning and testing the code.

Done!

**Review by ridsuteri — COMMENTED** [review]
@kalashvasaniya manifest file is missing :(

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya manifest file is missing :(

Added :)

**Review by ridsuteri — APPROVED** [review]
good job @kalashvasaniya

**Comment by kalashvasaniya** [comment]
> good job @kalashvasaniya

Thanks :)

**Pull request merged**
