### PR TITLE
added links and tab saver extension

### LINKED ISSUE #71: Title: Links and Tabs saver extension
### Is your feature request related to a problem? Please describe.

Hello @ridsuteri,
I want to add a Links and Tabs saver extension to this repository.
Thanks and regards,
Gana Sai Teja,
A GSSOC Contributor :).

### Describe the solution you'd like.

This extension will help you to save links and tabs. This project is done in HTML, CSS, JavaScript

### Describe alternatives you've considered.

-GSSOC'22 :)

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by gana-18**
### 🛠️ Fixes Issue

 Closes #71 

### 👨‍💻 Changes proposed

Added files for links and tabs saver extension

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image
image

### CODE REVIEW

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@gana-18 I think you missed something, please check once again, I can't find any files in this PR

**Comment by ridsuteri** [comment]
@gana-18 any updates on this?

**Comment by gana-18** [comment]
hey @ridsuteri sorry for the late response
I can not understand why files are missing in this pr. Can I re-submit my pr?

**Comment by ridsuteri** [comment]
> hey @ridsuteri sorry for the late response I can not understand why files are missing in this pr. Can I re-submit my pr?

yes sure

**Comment by ridsuteri** [comment]
closing this one bcz PR #112 resolved this

**Pull request closed without merging**
