### PR TITLE
Number System Converter Extension

### PR DESCRIPTION
**Pull request by niteshjangid29**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [x] New UI has been Designed for this project.
- [x] Added New Features (Binary <--> Decimal <--> Octal <--> Hexadecimal <--> Binary).
- [x] All features are working properly.
- [x] Accept input(Hexadecimal) in both cases (lowercase & uppercase) and gives same result (uppercase) on both cases.
- [x] Created a new Logo for the extension with different sizes.
- [x] If inputs are correct getting correct output.
- [x] This PR does not contain plagiarized content.
- [x] This PR isn't a duplicate of a previous one and contain extra features.
- [x] The title of my pull request is a short description of the requested changes.

### New Logo for Extension
logo

#### All Conversion are working properly.
image

#### Demo Image of conversion from Octal to Hexadecimal
image

#### Correct Answer on Following Inputs
--> Binary [0-1]
--> Octal [0-7]
--> Decimal [0-9]
--> Hexadecimal [0-9] + [a-f] / [A-F]

### => Old UI of Extension
image

### =>New UI of Extension
Demo

### CODE REVIEW

**Comment by its-harsshhh** [comment]
@niteshjangid29 binary to any other number conversion is not working...please check your code!

**Review by its-harsshhh — CHANGES_REQUESTED** [review]
@niteshjangid29  this is looking goooodd but binary to any other number conversion is not working...its need to be addessed before getting merged!

**Comment by niteshjangid29** [comment]
It's working with me, Can you check again ?
If still not working, can you give me the input for which you are not getting answer.

### Binary to Decimal (10101010101010101010)
image

### Binary to Octal (10101010101010101010)
image

### Binary to Hexadecimal (10101010101010101010)
image

**Comment by niteshjangid29** [comment]
@its-harsshhh Can you check it again, because it is working for me.
If not working with you, can you give me the input for which you are not getting answer

**Comment by its-harsshhh** [comment]
@niteshjangid29  I review your code once again properly. It's working fine. Sorry for inconvenience

**Pull request merged**
