### PR TITLE
Calculate Age Chrome Extension:

### PR DESCRIPTION
**Pull request by Mrjoy832**
### 🛠️ Fixes Issue
- #196 

- Added html,css, Js code with Logo and tested on Chrome Web Extension .
### ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@praniti111 , @ridsuteri  , please check it

**Review by ridsuteri — CHANGES_REQUESTED** [review]
The months seem to be not working, please check once again
Screenshot (10)

**Comment by Mrjoy832** [comment]
> The months seem to be not working, please check once again
> Screenshot (10)
> 

Okay I will check

**Comment by Mrjoy832** [comment]
> The months seem to be not working, please check once again Screenshot (10)
Hey @ridsuteri , I had some bracket errors in JS..Now I have fixed it.
image
**Here is the Demo**
image

**Review by ridsuteri — APPROVED** [review]
good job @Mrjoy832 :)

**Pull request merged**
