### PR TITLE
Toxicity Classification Extension added

### PR DESCRIPTION
**Pull request by shreya024**
### 👨‍💻 Changes proposed

-Added html,css, js(and tensorflow.js) for toxicity classification extension
-Added images and manifest

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I have used tensorflow.js and googleapi for making the classification

## 📷 Screenshots

img0

img1

### CODE REVIEW

**Comment by ridsuteri** [comment]
@shreya024 There is some issue with the extensions

```
Error
Invalid value for 'content_security_policy'.
Could not load manifest.

```

Please check once again!

**Comment by ridsuteri** [comment]
@shreya024 There is some issue with the extensions

```
Error
Invalid value for 'content_security_policy'.
Could not load manifest.

```

Please check once again!

**Comment by shreya024** [comment]
> @shreya024 There is some issue with the extensions
> 
> ```
> Error
> Invalid value for 'content_security_policy'.
> Could not load manifest.
> ```
> 
> Please check once again!

I have tried to resolve the issue. It is working properly in my local .

https://user-images.githubusercontent.com/72400676/162883820-702dd99c-23a4-4990-91ea-7a6975d1a59a.mp4

**Comment by ridsuteri** [comment]
@shreya024 the extension is loading properly now, but unable to see the prediction even after waiting for quite some time. Please look into this and one quick suggestion, maybe you can add a loader icon till the prediction arrives

**Comment by shreya024** [comment]
> @shreya024 the extension is loading properly now, but unable to see the prediction even after waiting for quite some time. Please look into this and one quick suggestion, maybe you can add a loader icon till the prediction arrives

Sorry for the inconvience . I have added the loader and done some modificaions...should definitely work this time.The git guardian warning is because of my api key integrated in the fetch request without which the extension will not work.

**Review by ridsuteri — APPROVED** [review]
good job @shreya024, It's working great :)

**Comment by shreya024** [comment]
> good job @shreya024, It's working great :)

Thank you :)

**Pull request merged**
