### PR TITLE
docs: Add PR Template

### LINKED ISSUE #32: docs: Adding a Pull Request Template
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
Screenshot from 2022-03-01 17-54-32

- Contribution towards GSsoc`22, Thank you

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Fix Issue
Closes #32

### Changes
- Added PR Template

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
The issue isn't linked properly, please put it on the same line, for eg: Fixes #32

**Comment by Pradumnasaraf** [comment]
> The issue isn't linked properly, please put it on the same line, for eg: Fixes #32

Hey @KendallDoesCoding it is liked properly and working :).

**Comment by KendallDoesCoding** [comment]
> > The issue isn't linked properly, please put it on the same line, for eg: Fixes #32
> 
> Hey, @KendallDoesCoding it is linked properly and working :).

Uh no 
image

**Review by ridsuteri — APPROVED** [review]
looks good, good work @Pradumnasaraf :)

**Pull request merged**
