### PR TITLE
Motivation unlimited 1

### PR DESCRIPTION
**Pull request by nik132-eng**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by praniti111** [comment]
@nik132-eng I see that you have pushed all the files of the extension individually, I suggest you put all the files(.html,.css, .json)into a single folder, and then push the folder to your forked repo and make a pr again.

**Comment by nik132-eng** [comment]
ok sir

**Comment by nik132-eng** [comment]
@praniti111 sir is this ok now??

**Comment by ridsuteri** [comment]
closing this one since it is outdated!

**Pull request closed without merging**
