### PR TITLE
Adding Weight Conversion

### PR DESCRIPTION
**Pull request by kalashvasaniya**
Hey I made Weight Conversion Project Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

### CODE REVIEW

**Comment by praniti111** [comment]
@kalashvasaniya The name of the extension appears to be "Height Conversion" where as you have mentioned it to be "Weight Conversion Tool" please make the necessary changes in the manifest file.

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya The name of the extension appears to be "Height Conversion" where as you have mentioned it to be "Weight Conversion Tool" please make the necessary changes in the manifest file.

Okk sorry I will

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya The name of the extension appears to be "Height Conversion" where as you have mentioned it to be "Weight Conversion Tool" please make the necessary changes in the manifest file.

Done :)

**Review by ridsuteri — APPROVED** [review]
good job @kalashvasaniya :)

**Pull request merged**
