### PR TITLE
Added Exchange Rates of Top Trending Crypto Coins

### LINKED ISSUE #316: Crypto Currency - Chrome Extension
### Is your feature request related to a problem? Please describe.

- Exchange Rates of Top Trending Crypto Coins

### Describe the solution you'd like.

- Make a Chrome Extension for Exchange Rates of Top Trending Crypto Coins

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #316 
Review Required @ridsuteri @praniti111 

### 👨‍💻 Changes proposed
- Added Chrome Extension for Exchange Rates of Top Trending Crypto Coins

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 3 and GSSoC Label for this !

**Comment by hariketsheth** [comment]
@ridsuteri, This PR would be categorised as Level 3 since it includes implementation of Crypto and blockchain + comparisons to be made while projecting data to the user. Kindly check, if you feel the same - kindly request you to change the label. 

Thank you :)

**Comment by ridsuteri** [comment]
Umm @hariketsheth I think you have just used an API to fetch the details of the cryptocurrencies only...
and level 2 is good for this, Sorry can't make this a level 3 :(

**Comment by hariketsheth** [comment]
> Umm @hariketsheth I think you have just used an API to fetch the details of the cryptocurrencies only... and level 2 is good for this, Sorry can't make this a level 3 :(

Sure ! I understood. No issues
I have still some more ideas for Extensions. I can contribute still right ?

**Comment by ridsuteri** [comment]
> > Umm @hariketsheth I think you have just used an API to fetch the details of the cryptocurrencies only... and level 2 is good for this, Sorry can't make this a level 3 :(
> 
> Sure ! I understood. No issues I have still some more ideas for Extensions. I can contribute still right ?

yeah yeah go ahead

**Pull request merged**
