### PR TITLE
UI enhanced

### PR DESCRIPTION
**Pull request by VasuDevrani**
### 🛠️ Fixes Issue
Solved Issue #473 
Enhanced and changed  the website UI and code, advanced dark mode, solved bugs like image bug, improved responsiveness

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
Please merge the request

### CODE REVIEW

**Comment by VasuDevrani** [comment]
Please Note the changes I have made -
- deleted previous html, css, js files of website and created new ones
- changed the name of some folders just because Browser was not accepting names with spaces in between while rendering images...
- There are no changes anywhere else like chrome extension folders

**Comment by narayan954** [comment]
Can you resolve the conflicts? So it can be reviewed.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by narayan954 — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by VasuDevrani** [comment]
What's the issue? Do I need to anything here

**Comment by narayan954** [comment]
There were some merge conflicts that were to be resolved manually. I just did that and checked your work. It's great , Thanks for your contribution.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Review by narayan954 — COMMENTED** [review]
conflicts resolved

**Comment by VasuDevrani** [comment]
Thanks a lot.
Please deploy the website too...

**Comment by narayan954** [comment]
@ridsuteri  Can you please look into the deployment ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by narayan954** [comment]
@VasuDevrani it's because ,you didn't change the index.html but instead created home.html and github pages targets index.html.
I didn't notice it earlier as well.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by VasuDevrani** [comment]
Yeah... I was thinking about the same
Sorry for that

Then, should i create another pull req for the file rename?

**Comment by VasuDevrani** [comment]
Hey @narayan954 , I just saw into the repo, it contains some addtional files like stylehelp.js, index.html etc. I haven't created these, are older ones.

**Comment by narayan954** [comment]
@VasuDevrani I did some changes , can you confirm if they're the changes you expected ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by VasuDevrani** [comment]
@narayan954 
There are few errors yet
- some new extension folders are named with space like 'FOLDER  NAME', this space causes error while browser tries to access image location. Please remove the spaces in name and also add a contributing guideline stating this issue
- the names of files: about.html and help.html need to be amended in href links
   ***CHANGE*** 
Help.html -> help.html 
About.html -> about.html

- i guess you have changed the name of css files as well. This needs to be changed in css referral links in the html as well
- If you want me to do, i'll be happy to help

image

**Comment by narayan954** [comment]
Yeah, you're right, you can work on them but I think we need to raise a new issue mentioning these errors, especially the contributing guidelines.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by VasuDevrani** [comment]
No problem
I'd be more than happy to help...

**Pull request merged**
