### PR TITLE
Added Web IDE for Github

### LINKED ISSUE #353: Web IDE for GitHub
### Is your feature request related to a problem? Please describe.

This extension adds to any GitHub repository a new drop down menu which offers links to a number of online services that allow viewing the source code of the repository in an IDE like interface.

### Describe the solution you'd like.

A implementation in the form of Chrome Extension

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #353 
### 👨‍💻 Changes proposed
This extension adds to any GitHub repository a new drop down menu which offers links to a number of online services that allow viewing the source code of the repository in an IDE like interface.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
- Requesting for adding Level 3 for this.

## 📷 Screenshots
image

image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@ridsuteri Please review

**Comment by hariketsheth** [comment]
@Akshima-Ghai Please review this. Since this adds utility to all Github repositories, Request for Level 3

**Comment by ridsuteri** [comment]
Umm @hariketsheth One can easily open this editor by pressing '.' on any repository...
Do you think there is need of this heavy extension in such cases?

**Comment by ridsuteri** [comment]
> > Umm @hariketsheth One can easily open this editor by pressing '.' on any repository... Do you think there is need of this heavy extension in such cases?
> 
> Just for Github Dev you can press '.' and do that
> 
> But according to this image attached here, you have quite more options available that are implemented as well image

cool

**Pull request merged**
