### PR TITLE
Puzzle Game eXTENSION

### LINKED ISSUE #148: Puzzle Game chrome extension
### Is your feature request related to a problem? Please describe.

Most of us sometimes get bored while surfing internet

### Describe the solution you'd like.

We have a solution of it by making a Puzzle Game chrome extension 
I would like to solve the issue
I'm a GSSOC22 contributor

### Describe alternatives you've considered.

puzzle

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by iamrahulmahato**
### 🛠️ Fixes Issue

 Closes #148

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2022-04-08 030547
Screenshot 2022-04-08 030523

### CODE REVIEW

**Comment by praniti111** [comment]
@iamrahulmahato I see the project folder name is Puzzle Game, but the manifest file name has some other project name, also the folder name where the manifest file is present is different, do make the necessary changes, 
please check all the details before raising the pr.

**Comment by iamrahulmahato** [comment]
@praniti111 my mistakenly i have added the manifest file of the joke project but now deleted and everything is aligned
Screenshot 2022-04-09 020919

**Comment by iamrahulmahato** [comment]
@ridsuteri my mistake I have deleted the random joke manifest file so have made another pr #171 and added it

**Comment by ridsuteri** [comment]
since this PR is redundant, hence closing this one

**Pull request closed without merging**
