### PR TITLE
GRE Vocab : These Extension help the GRE aspirants get all vocab Word + Definition

### PR DESCRIPTION
**Pull request by RiyaBhandari-2811**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
GREVocabImg

https://user-images.githubusercontent.com/85748264/159780847-bb4e54d2-4f33-4ca1-8284-ef04ee0e06e8.mp4

### CODE REVIEW

**Comment by RiyaBhandari-2811** [comment]
@ridsuteri  I've Done my work , would you pls take some time and review it .

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@RiyaBhandari-2811 the extension fails to load bcz the manifest file is missing :((

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811 the extension fails to load bcz the manifest file is missing :((

@ridsuteri sorry for inconvenience  , now every thing is in build folder so while loading the extension just load Build folder that's it .

**Review by ridsuteri — APPROVED** [review]
good job @RiyaBhandari-2811, Thanks for contributing :)

**Comment by RiyaBhandari-2811** [comment]
> good job @RiyaBhandari-2811, Thanks for contributing :)

Thank you so much @ridsuteri 🤗💯

**Pull request merged**
