### PR TITLE
Water-Break

### PR DESCRIPTION
**Pull request by kalashvasaniya**
This extension reminds you after each 35 minutes to take a break and drink water. As soon as the countdown ends the extension alerts you with an alarm sound.

### CODE REVIEW

**Comment by MurtazaMister** [comment]
@kalashvasaniya, nice one 👏🏻, just make sure that it runs in the background, because every time we close this extension, the timer resets.

**Comment by kalashvasaniya** [comment]
@MurtazaMister I think it runs in the background,
Its my first PR so pls. merge to main branch!😇

**Review by ridsuteri — APPROVED** [review]
looks good @kalashvasaniya, but the extension doesn't run in bg...
but since it is your first contribution I am merging it now...
Try to fix this issue later by opening a fresh issue :)

**Comment by kalashvasaniya** [comment]
> looks good @kalashvasaniya, but the extension doesn't run in bg...
> but since it is your first contribution I am merging it now...
> Try to fix this issue later by opening a fresh issue :)

Thank you so much!

**Pull request merged**
