### PR TITLE
Flight Tracker Extension added

### PR DESCRIPTION
**Pull request by shreya024**
### 👨‍💻 Changes proposed
Added images,html,css,js,manifest and logo for Flight Tracker extension

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I would like to add a second PR for choosing the country and giving exact flight status like arrived or in transit

## 📷 Screenshots
img1

### CODE REVIEW

**Review by ridsuteri — COMMENTED** [review]
@shreya024 I don't think this extension is of much use If we can't search for our desired flight...
Can you add a search box to search the details as per the given data?

**Comment by shreya024** [comment]
> @shreya024 I don't think this extension is of much use If we can't search for our desired flight... Can you add a search box to search the details as per the given data?

Sure is it okay if I add it in the next PR?or I have to do it in this one only?

**Comment by ridsuteri** [comment]
> > @shreya024 I don't think this extension is of much use If we can't search for our desired flight... Can you add a search box to search the details as per the given data?
> 
> Sure is it okay if I add it in the next PR?or I have to do it in this one only?

Do it in this one, since without this feature, merging this won't make much sense

**Comment by shreya024** [comment]
> > > @shreya024 I don't think this extension is of much use If we can't search for our desired flight... Can you add a search box to search the details as per the given data?
> > 
> > 
> > Sure is it okay if I add it in the next PR?or I have to do it in this one only?
> 
> Do it in this one, since without this feature, merging this won't make much sense

Okay the api I'm using provides search option for flight number or flight date...which one should I do?

**Comment by ridsuteri** [comment]
sorry @shreya024 won't be able to merge it :(

**Pull request closed without merging**
