### PR TITLE
Added Extension for Developers

### LINKED ISSUE #339: Chrome Extension for Developers
### Is your feature request related to a problem? Please describe.

- This extension finds frontend developer keywords and highlights them.
- Useful for users looking for frontend developer jobs

### Describe the solution you'd like.

- Would like to implement a Chrome Extension for the same

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

.

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #339 

### 👨‍💻 Changes proposed
- This extension finds frontend developer keywords and highlights them.
- Useful for users looking for frontend developer jobs

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@praniti111 @ridsuteri 
Can you Review this PR

**Comment by praniti111** [comment]
@hariketsheth
Extensions - Google Chrome 23-05-2022 19_11_33
 The extension "developer-color" is not accessible, also please attach the screenshots of the actual working of the project.

**Comment by hariketsheth** [comment]
@ridsuteri Please review

**Comment by ridsuteri** [comment]
@hariketsheth again, if this extension just highlights a word, which can simply be done using CTRL+F, 
is there any need for such an extension?

**Comment by hariketsheth** [comment]
> @hariketsheth again, if this extension just highlights a word, which can simply be done using CTRL+F, is there any need for such an extension?

It highlights all the terms applicable for developers 

https://user-images.githubusercontent.com/72455881/170179399-90645018-3d06-4ef0-8852-25b6b9b286ef.mp4

**Comment by ridsuteri** [comment]
I can see only front-end and backend keywords in the file...
In that case you can add more keywords to the file..
Also this PR has 2-3 other folders added, Please remove them as well

**Comment by hariketsheth** [comment]
> I can see only front-end and backend keywords in the file... In that case you can add more keywords to the file.. Also this PR has 2-3 other folders added, Please remove them as well

I have added **new 34 developer words**. Please proceed with Review, @ridsuteri

**Review by ridsuteri — CHANGES_REQUESTED** [review]
@hariketsheth I think you have added openNewTabsonLeft and sketchify folders into this PR by mistake, Please remove them

**Comment by hariketsheth** [comment]
Proceed with Review, Updated @ridsuteri 👍🏻

**Review by ridsuteri — APPROVED** [review]

**Pull request merged**
