### PR TITLE
type color change

### PR DESCRIPTION
**Pull request by DragonUncaged**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by praniti111** [comment]
@DragonUncaged Does this extension only work on google searches?

**Comment by DragonUncaged** [comment]
> @DragonUncaged Does this extension only work on google searches?

It works on other websites also but as the background design of some website has multiple layers. That kind of website are difficult to change entirely.

**Comment by ridsuteri** [comment]
@DragonUncaged a similar extension exists with the name of background color changer...
is it any different from that one?

**Comment by DragonUncaged** [comment]
> Reference in ne

I did Not Found any extension Background Color Changer

**Comment by ridsuteri** [comment]
> 

Oh my bad, I remember it was added by prathima, but maybe we might have reverted it. So go on and thanks for cross-checking it :)

**Review by ridsuteri — APPROVED** [review]

**Pull request merged**
