### PR TITLE
Live CSS Style Editor Implemented

### LINKED ISSUE #350: Live CSS, Less, SASS Editor
### Is your feature request related to a problem? Please describe.

- Want to implement a Chrome Extension that helps developer to change the CSS / Styling codes on any website and see the preview live by seeing the output. 

### Describe the solution you'd like.

- A Chrome Extension
- Kindly assign this issue to me @praniti111 @r

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #350

### 👨‍💻 Changes proposed
- Implemented a Live CSS Editor - applicable on all website. 
- Helps developer see a live CSS Change and effect on the Webpage

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
- Requesting for adding Level 3 for this. Since this required Complex Implementation of Separate editor and options + manipulating browser settings and manipulate the actual CSS of rendered website page

## 📷 Screenshots
image

image

image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@ridsuteri Please review

**Comment by hariketsheth** [comment]
@Akshima-Ghai Please review this. Since this adds utility to all websites (CSS / SASS Styling), Request for Level 3

**Review by praniti111 — APPROVED** [review]
good work @hariketsheth

**Comment by hariketsheth** [comment]
@ridsuteri @Akshima-Ghai @praniti111 but I feel this would be a Level 3 PR since it is a utility extension that helps Developers to change the CSS dynamically and directly change the page look

**Comment by hariketsheth** [comment]
@ridsuteri I feel this would be a Level 3 PR

**Pull request merged**
