### PR TITLE
Added Sketchify Chrome Extension

### LINKED ISSUE #332: Sketchify - Chrome Extension
### Is your feature request related to a problem? Please describe.

- A Chrome Extension that would help artistic people for sketching purposes

### Describe the solution you'd like.

- A chrome extension would help solve this issue

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

.

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #332 

### 👨‍💻 Changes proposed
- A chrome extension for Sketching is implemented successfully

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

Review Requested @ridsuteri

### CODE REVIEW

**Comment by hariketsheth** [comment]
@praniti111 @ridsuteri 
Can you Review this PR

**Comment by hariketsheth** [comment]
@ridsuteri Please review

**Comment by hariketsheth** [comment]
@Akshima-Ghai Please review this PR

image



Since this adds a lot of tools and options for users to sketch and make notes during an particular event, I would request you to give Level 3. It has saving options, colors, shapes, paint, highlight, lines

**Comment by hariketsheth** [comment]
@Akshima-Ghai @ridsuteri Please review

**Comment by praniti111** [comment]
@hariketsheth The extension isn't working, also please attach the screenshots or video of the extension you have opened after loading it from manage extensions from your chrome browser.

**Comment by hariketsheth** [comment]
https://user-images.githubusercontent.com/72455881/170180063-af422964-f3c8-49b5-a3f8-9672c665e2bd.mp4

@praniti111 @ridsuteri

**Review by ridsuteri — APPROVED** [review]

**Pull request merged**
