### PR TITLE
Adding user taking form

### PR DESCRIPTION
**Pull request by kalashvasaniya**
This is biggest project I made in girlscript challenge Lol :)
This is user taking form made with html, css & javascript,
I have to work on both front-end as well as back-end,
I used formspree tool to send mail directly to the user!
if you use this extension and fill the form info directly come to my inbox!
currently I'm using my e-mail so if someone fill that form its come to my inbox. 
ps: video is long!
~ if you want some changes & improvement then tell I will do it! :)
https://user-images.githubusercontent.com/88212870/163348433-afa16d2c-e3cb-4f8c-9c76-93ca1486ca36.mov

### CODE REVIEW

**Comment by ridsuteri** [comment]
> This is biggest project I made in girlscript challenge Lol :) This is user taking form made with html, css & javascript, I have to work on both front-end as well as back-end, I used formspree tool to send mail directly to the user! if you use this extension and fill the form info directly come to my inbox! currently I'm using my e-mail so if someone fill that form its come to my inbox. ps: video is long! ~ if you want some changes & improvement then tell I will do it! :) https://user-images.githubusercontent.com/88212870/163348433-afa16d2c-e3cb-4f8c-9c76-93ca1486ca36.mov

@kalashvasaniya the design and implementation look stunning, but I am unable to receive any mail even after waiting for quite some time now, Please look into this and also maybe you can add a little loader icon until the mail is sent

**Comment by kalashvasaniya** [comment]
> > This is biggest project I made in girlscript challenge Lol :) This is user taking form made with html, css & javascript, I have to work on both front-end as well as back-end, I used formspree tool to send mail directly to the user! if you use this extension and fill the form info directly come to my inbox! currently I'm using my e-mail so if someone fill that form its come to my inbox. ps: video is long! ~ if you want some changes & improvement then tell I will do it! :) https://user-images.githubusercontent.com/88212870/163348433-afa16d2c-e3cb-4f8c-9c76-93ca1486ca36.mov
> 
> @kalashvasaniya the design and implementation look stunning, but I am unable to receive any mail even after waiting for quite some time now, Please look into this and also maybe you can add a little loader icon until the mail is sent

@ridsuteri I use Formspree website to link with my extension & I use my email that's why Only I recive mail If anyone fills it!,
if you want that you recive mail then you have to attach your mail in the code(index.html) & Ya I try to add loader icon.
Screenshot 2022-04-16 at 10 45 35 AM
Screenshot 2022-04-16 at 10 45 26 AM

**Comment by ridsuteri** [comment]
@kalashvasaniya got your point, in that case, I think you need to maintain a proper readme for this extension and leave the space to add email/token in the code itself.
So that the user can easily figure out the customizations and can use the details as per his/her needs.

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya got your point, in that case, I think you need to maintain a proper readme for this extension and leave the space to add email/token in the code itself.
> So that the user can easily figure out the customizations and can use the details as per his/her needs.

Yaa, sure I made readme.md file today itself with proper given detail & add loader icon also!

**Comment by kalashvasaniya** [comment]
> > @kalashvasaniya got your point, in that case, I think you need to maintain a proper readme for this extension and leave the space to add email/token in the code itself.
> > So that the user can easily figure out the customizations and can use the details as per his/her needs.
> 
> Yaa, sure I made readme.md file today itself with proper given detail & add loader icon also!

I'm Trying to add loader but loader not working on extension so I made it different if you click on submit it show "Success"
https://user-images.githubusercontent.com/88212870/163672861-48da2f3c-2a43-4224-b897-f34b86d6c68f.mov

**Comment by kalashvasaniya** [comment]
> > @kalashvasaniya got your point, in that case, I think you need to maintain a proper readme for this extension and leave the space to add email/token in the code itself.
> > So that the user can easily figure out the customizations and can use the details as per his/her needs.
> 
> Yaa, sure I made readme.md file today itself with proper given detail & add loader icon also!

Readme file added & after submit waiting time is over!

**Review by ridsuteri — APPROVED** [review]
good job @kalashvasaniya :))

**Comment by kalashvasaniya** [comment]
> good job @kalashvasaniya :))

Thank you 👍

**Pull request merged**
