### PR TITLE
Facts Extension

### LINKED ISSUE #257: Facts Extension
### Is your feature request related to a problem? Please describe.

Facts Extension

### Describe the solution you'd like.

I will make a Facts Extension in which the user will get to know about a fascinating fact and this will enhance the user's knowledge.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.
@praniti111 @ridsuteri

### PR DESCRIPTION
**Pull request by Sukriti-m**
### 🛠️ Fixes Issue

Closes #257 

### 👨‍💻 Changes proposed

I have added the extension.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

@ridsuteri @praniti111 @Akshima-Ghai  Please review it.

## 📷 Screenshots/Videos

https://user-images.githubusercontent.com/93239528/167875706-f171e360-2fac-4d3e-8204-4223ecf01665.mp4

### CODE REVIEW

**Comment by Akshima-Ghai** [comment]
great work @Sukriti-m

**Comment by Sukriti-m** [comment]
> great work @Sukriti-m

Why did you closed this PR? Are there any changes which are to be made, only then it will be merged?

**Comment by Akshima-Ghai** [comment]
sorry about the confusion @Sukriti-m

**Comment by Sukriti-m** [comment]
> sorry about the confusion @Sukriti-m

No problem. Thank you. 😄

**Pull request merged**
