### PR TITLE
Sports News Tracker - Chrome Extension Added 

### LINKED ISSUE #318: Sport News Chrome Extension
### Is your feature request related to a problem? Please describe.

- Extension required for Sport News

### Describe the solution you'd like.

- A Chrome Extension required for Sport News (Latest)

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #318 
Review requested from @ridsuteri 

### 👨‍💻 Changes proposed
- Chrome Extension Added for News Tracking - Sports 

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by hariketsheth** [comment]
Request you to add Level 2 and GSSoC Label for this !

**Comment by omrajsharma** [comment]
Hey Hariketsheth,
This extension is for sports news or crypto news?

**Comment by hariketsheth** [comment]
> Hey Hariketsheth, This extension is for sports news or crypto news?

Sport News, This would show the Matches for the day / If any team won / All the news related to Sports

**Comment by ridsuteri** [comment]
@hariketsheth since the news extension also provides these sports-related news hence I am closing this one :(

**Pull request closed without merging**
