### PR TITLE
Google Docs Viewer List - Chrome Extension

### LINKED ISSUE #374: Google Docs List Viewer
### Is your feature request related to a problem? Please describe.

Demonstrates how to use OAuth to connect the Google Documents List Data API.

### Describe the solution you'd like.

A Chrome Extension to be implemented

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by hariketsheth**
### 🛠️ Fixes Issue
Fixes #374 

### 👨‍💻 Changes proposed
Demonstrates how to use OAuth to connect the Google Documents List Data API.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@Akshima-Ghai @ridsuteri Please review

**Review by ridsuteri — COMMENTED** [review]
@hariketsheth how will this work? 
please add a demo

**Comment by hariketsheth** [comment]
> @hariketsheth how will this work? please add a demo

Here, @ridsuteri 

## Enable the Extension
image

## Then go to websites where PDF, DOC Files are sent
image


## Click on the Icon Visible
image

It will automatically add the document / File to your Google Drive.

**Comment by hariketsheth** [comment]
@ridsuteri Please proceed with review

**Comment by hariketsheth** [comment]
@ridsuteri Can you please reopen this PR. I don't know why it was closed

**Review by ridsuteri — APPROVED** [review]

**Pull request merged**
